name: "GSA/grace-paas-network"
description: "The GRACE PaaS Network module creates the the network resources required for a basic GRACE PaaS account."
license: cc0-1.0
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
    - grace-paas
contact:
    email: grace-staff@gsa.gov
